### PR TITLE
Add a primary flag to locations

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by marlo-longley** [comment]
Hey @cbeer -- I checked this out and have a couple questions/thoughts 

-- When selecting the checkbox to make something primary, the changes didn't persist unless I added `:primary` to this list https://github.com/sul-dlss/library_hours_rails/blob/1b5afafe2df53b22dd8002e4583e709fcacfc096/app/controllers/libraries_controller.rb#L87 for both the libraries and locations controllers

-- Should we make this attribute editable from the library form as well? Or just in location form?

-- Should there be any visual indication that a location is primary?

-- Where in the API can I see this? I wasn't having luck.

**Comment by cbeer** [comment]
Thanks for the fixes.


> There is nothing preventing 2 locations from being selected primary

True. There number of people with access is very small and the worst thing that happens is the wrong primary location is picked.

> Where in the API can I see this? I wasn't having luck.

[/libraries.json ](http://library-hours.stanford.edu/libraries.json) is the entry point SWS is using, and gives you something like:

```
{"data"=>
  [{"type"=>"libraries",
    "id"=>"green",
    "attributes"=>
     {"name"=>"Some Library",
      "primary_location"=>"green/some-location",
      "hours"=>
       [{"day"=>"2023-01-15", "weekday"=>"Sunday", "closed"=>true},
        {"day"=>"2023-01-16", "weekday"=>"Monday", "closed"=>true},
        {"day"=>"2023-01-17", "weekday"=>"Tuesday", "closed"=>true},
        {"day"=>"2023-01-18", "weekday"=>"Wednesday", "closed"=>true},
        {"day"=>"2023-01-19", "weekday"=>"Thursday", "opens_at"=>"2023-01-19T00:00:00.000-08:00", "closes_at"=>"2023-01-19T23:59:59.999-08:00", "type"=>"Open", "closed"=>false},
        {"day"=>"2023-01-20", "weekday"=>"Friday", "closed"=>true},
        {"day"=>"2023-01-21", "weekday"=>"Saturday", "closed"=>true}]},
    "relationships"=>{"locations"=>{"data"=>[{"type"=>"locations", "id"=>"green/some-location"}], "links"=>{"related"=>"http://www.example.com/libraries/green/locations"}}},
    "links"=>{"self"=>"http://www.example.com/libraries/green"}}],
 "included"=>
  [{"type"=>"locations",
    "id"=>"green/some-location",
    "attributes"=>
     {"name"=>"Some Location",
      "primary"=>true,
      "hours"=>
       [{"day"=>"2023-01-15", "weekday"=>"Sunday", "closed"=>true},
        {"day"=>"2023-01-16", "weekday"=>"Monday", "closed"=>true},
        {"day"=>"2023-01-17", "weekday"=>"Tuesday", "closed"=>true},
        {"day"=>"2023-01-18", "weekday"=>"Wednesday", "closed"=>true},
        {"day"=>"2023-01-19", "weekday"=>"Thursday", "opens_at"=>"2023-01-19T00:00:00.000-08:00", "closes_at"=>"2023-01-19T23:59:59.999-08:00", "type"=>"Open", "closed"=>false},
        {"day"=>"2023-01-20", "weekday"=>"Friday", "closed"=>true},
        {"day"=>"2023-01-21", "weekday"=>"Saturday", "closed"=>true}]},
    "relationships"=>{"library"=>{"links"=>{"related"=>"http://www.example.com/libraries/green"}, "data"=>{"type"=>"libraries", "id"=>"green"}}},
    "links"=>{"self"=>"http://www.example.com/libraries/green/locations/some-location"}}]}
```

**Comment by marlo-longley** [comment]
Thanks @cbeer . Ok given your answer about small number of users this may be irrelevant, but my last thought is wondering if there should be any visual indication that something is primary.

**Comment by cbeer** [comment]
If you have a good idea, go for it.

**Comment by marlo-longley** [comment]
@cbeer I think maybe that's out of scope for this when I think about it more. This is really supposed to be an API feature for SWS. I was mostly concerned about admins/editors having a visual indication, and they do in the form checkbox. For end users browsing the site, I think a visual could be confusing without the right phrasing. So I'm good to leave it for now.

**Review by marlo-longley — APPROVED** [review]

**Comment by marlo-longley** [comment]
Ref #441

**Pull request merged**
